### ISSUE TITLE
net_iCompression==1 crashes

### ISSUE THREAD

**Issue by dyrverE** [rcgordon/Serious-Engine#15]
//uses the LZRW1 compressor algorithm by Ross Williams.

Game is both faster and more stable using zlib ==2 or really no networkmessage compression at all ==0.

Serious-Engine/Sources/Engine/Network/Compression.cpp
the issue seems to stem from line 311, 'p' does not get a memory area that is accessible. I'll work on a fresh gdb log after work if you need one.

**Comment by icculus** [comment]
I just pushed what I think is a fix from this (at least, this bug went from 100% reproducible to not at all).

That fix is https://github.com/rcgordon/Serious-Engine/commit/a0595204d472fdc852fc8b46dc0c4392f96a330b
