### ISSUE TITLE
GameAgent - list servers  bugfix.

### ISSUE THREAD

**Issue by RocketersAlex** [rcgordon/Serious-Engine#16]
After compiling the code I notice that is not given a list of servers from the master server.
The fix is to move the five lines below conditions:
# ifdef PLATFORM_WIN32

....
# endif

![patch](https://cloud.githubusercontent.com/assets/17551181/14422564/25119d64-ffe0-11e5-9f5a-0477fbd7ef70.png)
Variable _szBuffer need for adoption of a reply from the game server.
After fixing the server list is visible:

![servers](https://cloud.githubusercontent.com/assets/17551181/14422650/8bbfc8d8-ffe0-11e5-880b-be58139dc0e8.png)

And thank you for your great work

**Comment by icculus** [comment]
I merged your pull request for this (thanks again!), so I'm closing this issue as fixed.
