### ISSUE TITLE
Separate versions for sdl1 and sdl2

### ISSUE THREAD

**Issue by ghost** [rcgordon/Serious-Engine#21]
Is it possible to define both sdl1 and sdl2 builds in your main branch? Or possibly keep a branch as an archive of the latest sdl1 version, along with any important recent updates?

**Comment by icculus** [comment]
I don't have any plans to do this. One could certainly branch from a few revisions ago, but I don't want to encourage that. SDL 1.2 is a dead API; the only reason it was in here at all is because it was current 15 years ago when I originally wrote that code.

**Comment by ericwomer** [comment]
@box-tortoise I am curious, why do you want to use SDL1? is there a mobile system that only uses SDL1 or is this a hardware limitation?
