### ISSUE TITLE
Cannot open file `/home/user/Desktop/Classes/Player.ecl` error

### ISSUE THREAD

**Issue by coleshores** [rcgordon/Serious-Engine#57]
I am getting a Cannot open file `/home/user/Desktop/Classes/Player.ecl` (no such file or directory) error.  I tried to look for that file and it isnt on my system.
What should I do next?
Thanks in advance,
Cole

**Comment by yamgent** [comment]
May I know the location of your 'ssam' executable?

**Comment by coleshores** [comment]
Sure, its in here with my datafiles
~/Desktop/Serious Sam Classic The First Encounter

**Comment by yamgent** [comment]
You need to put `ssam` into the `Bin` directory.

```
.../SSFE/
     |--- SE1_10.gro
     |--- some_other_gros.gro
     |--- ...
     |--- Bin/
           |--- ssam
           |--- ...
           |--- Debug/
                   |--- libEntitiesD.so
                   |--- ...
```

**Comment by Elinvention** [comment]
Hi, I compiled Serious Engine with cmake, make and copied `ssam` into `Bin`, but now it complains about `libEntitiesD.so`. I can't find that file, but I have `libEntitiesMPD.so`. After this an assertion fails as in #55.

**Comment by coleshores** [comment]
I am having this issue as well.  How did you solve it?

**Comment by DanielGibson** [comment]
as I said in the other issue, the *MP stuff is for the second encounter, to build the engine for the first encounter pass `-DTFE=TRUE` to cmake

**Comment by coleshores** [comment]
I applied the changes to fix the assertion errors and added the -DTFE=TRUE flag.  Compiles down to ssam-tfe 

 Now getting a Cannot open file `/home/user/Desktop/Serious Sam Classic The First Encounter/TexturesMP/General/MenuBack.tex` (no such file or directory)

if *MP is second encounter stuff.  maybe something went wrong, or should I close this ticket and create a new one?

**Comment by Elinvention** [comment]
I found out you have to copy `SE1_10.gro` too. I think we need to write a guide to help newbies make TFE and TSE work on linux.

**Comment by coleshores** [comment]
Thanks! That was helpful, I got it to work now on my Tegra K1 Chromebook after I moved that SE1_10.gro to the top level folder.
.../SSFE/
     |--- SE1_10.gro

**Comment by DanielGibson** [comment]
> I think we need to write a guide to help newbies make TFE and TSE work on linux.

yeah, improving the README sounds like a good idea - go for it :)

**Comment by yamgent** [comment]
I have a guide lying around, but I was hesitated to add it initially because I felt that the building process would drastically evolve as time goes on, since the current building process doesn't seem to be that refined atm.

But in case anyone's interested, it's in PR #61.
