### ISSUE TITLE
BulletHitGrass.wav (No such file or directory)

### ISSUE THREAD

**Issue by Elinvention** [rcgordon/Serious-Engine#58]
I applied #56 to solve the assertion errors, but now I have a new problem when I try to start Serious Sam The First Encounter:

```
Cannot open file `/home/elia/Serious Sam The First Encounter/SoundsMP/Weapons/BulletHitGrass.wav` (No such file or directory) ()
```

Indeed there is no SoundsMP folder :cry:

**Comment by DanielGibson** [comment]
the *MP stuff is for the second encounter.
when calling cmake, pass `-DTFE=TRUE` as commandline argument, to enable building for first encounter instead of second encounter.

**Comment by Elinvention** [comment]
Ok, I tried but it still complains about *MP stuff: `TexturesMP/General/MenuBack.tex`...

I also tried Serious Sam The Second Encounter and it works fine without `-DTFE=TRUE`.

**Comment by DanielGibson** [comment]
then you did something wrong.
-DTFE=TRUE is for first encounter (only), -DTFE=FALSE (which is default) is for second encounter only.
make sure to run cmake with that option, afterwards rebuild and copy ssam and the Debug/ dir to your sesam-firstencounter/Bin/ dir.

**Comment by Elinvention** [comment]
Ok, now it works, TFE requires an additional file `SE1_10.gro` and I forgot to copy it too. Thank you for your help.
