### ISSUE TITLE
Some problems with buildinng on linux

### ISSUE THREAD

**Issue by mad-student** [rcgordon/Serious-Engine#73]
I started command Sources/build-linux64.sh and got this:
Will build with 'make -j4' ... please edit this script if incorrect.

rm -rf cmake-build

mkdir cmake-build

cd cmake-build

cmake -DCMAKE_BUILD_TYPE=Debug ..
CMake Error: The source directory "/Serious-Engine" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Found CMakeLists.txt in "/Serious-Engine/Sources" and copy it to "/Serious-Engine". 

After that restart command and got this:
Will build with 'make -j4' ... please edit this script if incorrect.

rm -rf cmake-build

mkdir cmake-build

cd cmake-build

cmake -DCMAKE_BUILD_TYPE=Debug ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:2 (project):
No CMAKE_CXX_COMPILER could be found.

Tell CMake where to find the compiler by setting either the environment
variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/Serious-Engine/cmake-build/CMakeFiles/CMakeOutput.log".
See also "/Serious-Engine/cmake-build/CMakeFiles/CMakeError.log".

Is there any possibility to fix that error?
P.S. Sorry for my English. This language isn't native for me.
I use Lubuntu 18.04 if this matter.

**Comment by yamgent** [comment]
You will need to run the build script inside the `Sources` folder, not outside it. In other words, you should be doing this:

```
cd Sources
./build-linux64.sh
```

**Comment by DanielGibson** [comment]
it also looks like no C++ compiler is installed

if you enter `g++` on the commandline, what happens? if it's command not found, try `sudo apt-get install build-essential`, which should install gcc, g++, make and some basic system headers

you'll also (at least) need the `libsdl2-dev` package

**Comment by mad-student** [comment]
I install packages that you said and also installed bison and also installed bison and flex (because thay was mentioned as required packages) run command "./build-linux64.sh" from Sources directory and got this:

Will build with 'make -j4' ... please edit this script if incorrect.
+ rm -rf cmake-build
+ mkdir cmake-build
+ cd cmake-build
+ cmake -DCMAKE_BUILD_TYPE=Debug ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so;-lpthread  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
WARNING,re-enable some of the warnings some day!
-- Using assembler code (when available)
-- Not using i386 nasm ASM
-- Configuring done
-- Generating done
-- Build files have been written to: /home/psycho/Serious-Engine/Sources/cmake-build
+ make -j4
[  0%] Generating ../Ecc/Scanner.cpp
[  0%] Generating ../Ecc/Parser.cpp, ../Ecc/Parser.hpp
Ecc/Parser.y:1435 parser name defined to default :"parse"
Ecc/Parser.y contains 86 shift/reduce conflicts and 1 reduce/reduce conflict.
[  0%] Generating ../Ecc/Parser.h
Error copying file "Ecc/Parser.hpp" to "Ecc/Parser.h".
CMakeFiles/ecc.dir/build.make:68: recipe for target '../Ecc/Parser.h' failed
make[2]: *** [../Ecc/Parser.h] Error 1
make[2]: *** Удаляется файл «../Ecc/Parser.h»
CMakeFiles/Makefile2:137: recipe for target 'CMakeFiles/ecc.dir/all' failed
make[1]: *** [CMakeFiles/ecc.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Maybe I don't have some other packages that needed for building binaries. I don't have much expiriece in Linux.

**Comment by yamgent** [comment]
> ```
> [ 0%] Generating ../Ecc/Scanner.cpp
> [ 0%] Generating ../Ecc/Parser.cpp, ../Ecc/Parser.hpp
> Ecc/Parser.y:1435 parser name defined to default :"parse"
> Ecc/Parser.y contains 86 shift/reduce conflicts and 1 reduce/reduce conflict.
> [ 0%] Generating ../Ecc/Parser.h
> Error copying file "Ecc/Parser.hpp" to "Ecc/Parser.h".
> ```

That is quite a strange copying error, since the file is generated right before the copying is supposed to take place.

Try and delete all of these files inside your `Sources/Ecc/` folder if they exist:
* `Scanner.cpp`
* `Parser.cpp`
* `Parser.hpp`
* `Parser.h`

Then re-run `./build-linux64.sh`. Does it still show the same error?

**Comment by yamgent** [comment]
Also may I know the version of flex and bison that you are using? (via `flex --version` and `bison --version`)

**Comment by mad-student** [comment]
flex 2.6.4
bison (GNU Bison) 3.0.4
Also, sorry, I cheated a little and create 2 conversation at the same time: here and on fork from this engine by ptitSeb (https://github.com/ptitSeb/Serious-Engine/issues/3). Looks like it work fine. Thanks for the help - you are great, guys!
